### ISSUE TITLE
Typo found in word 'timetamps'

### ISSUE THREAD

**Issue by guizo792** [oracle/json-in-db#55]
While using this code, I encountered a typo in the files :
`YCSB/ycsb-soda/core/src/main/java/com/yahoo/ycsb/workloads/TimeSeriesWorkload.java`
`YCSB/ycsb-soda/core/src/main/java/site/ycsb/workloads/TimeSeriesWorkload.java`

The word `'timetamps'` was incorrectly used instead of `'timestamp'`. I have corrected this typo and opened a pull request referencing the corresponding issue number.

**Comment by jjspiegel** [comment]
This is branched from https://github.com/brianfrankcooper/YCSB so it would need to be fixed there.
